version: '3.9'

services:
  bot:
    image: bot
    build:
      context: .
      args:
        - GOVERSION=1.20.0
    environment:
      - ENV
    ports:
      - 8080:8080
    volumes:
      - .:/app
